### ISSUE TITLE
Normal to see just a purple background with outline?

### ISSUE THREAD

**Issue by FreeLikeGNU** [OpenSiege/OpenSiege#12]
![Screenshot_2020-09-24_10-06-37](https://user-images.githubusercontent.com/674095/94177025-ca686e80-fe4d-11ea-8ce2-6dac54278087.png)

This is what I get running on Ubuntu 20.04.

**Comment by OpenSiege** [comment]
Yes. I've updated the README.md to reflect this. You'll have to pass a state to the command line.

```./OpenSiege --state="RegionTestState"```

**Comment by FreeLikeGNU** [comment]
Cool, the command line works differently on Linux: ```./OpenSiege --state RegionTestState```

**Comment by OpenSiege** [comment]
It works the same way on windows. I fixed the doc to reflect. Nice to see it rendering.

**Comment by FreeLikeGNU** [comment]
Almost brought a tear to my eyes!  Thank you for making this!
